package com.example.demo.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.DBRef;
import org.springframework.data.mongodb.core.mapping.Document;
import lombok.*;
import java.time.LocalDateTime;

@Document(collection = "orders")
@Data            // generates getters + setters
@NoArgsConstructor
@AllArgsConstructor
public class Order {

    @Id
    private String id;
    private String orderNumber;
    private LocalDateTime orderDate = LocalDateTime.now();
    private double totalAmount;

    private User user;   // <-- setter generated by Lombok

    private String userId;
}
